<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-EGT0M14" failures="0" tests="3" name="rahulshettyacademy.SeleniumFrameWorkDesign.tests.Submitorder" time="48.971" errors="1" timestamp="2024-02-16T21:36:13 IST" skipped="0">
  <testcase classname="rahulshettyacademy.SeleniumFrameWorkDesign.tests.Submitorder" name="submitorder" time="26.043"/>
  <testcase classname="rahulshettyacademy.SeleniumFrameWorkDesign.tests.Submitorder" name="validateOrder" time="9.230">
    <error message="
[public void rahulshettyacademy.SeleniumFrameWorkDesign.tests.Submitorder.validateOrder(java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: validateOrder([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2])
Arguments: [(java.util.HashMap) {password=Ria@1991, product=IPHONE 13 PRO, email=achokroborty@gmail.com}]" type="org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void rahulshettyacademy.SeleniumFrameWorkDesign.tests.Submitorder.validateOrder(java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: validateOrder([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2])
Arguments: [(java.util.HashMap) {password=Ria@1991, product=IPHONE 13 PRO, email=achokroborty@gmail.com}]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:918)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
    </error>
  </testcase> <!-- validateOrder -->
  <testcase classname="rahulshettyacademy.SeleniumFrameWorkDesign.tests.Submitorder" name="submitorder" time="13.698"/>
</testsuite> <!-- rahulshettyacademy.SeleniumFrameWorkDesign.tests.Submitorder -->
